DROP TABLE IF EXISTS signatures;
DROP TABLE IF EXISTS users;

CREATE TABLE users(
   id SERIAL PRIMARY KEY,
   first VARCHAR NOT NULL CHECK (first != ''),
   last VARCHAR NOT NULL CHECK (last != ''),
   email VARCHAR NOT NULL UNIQUE,
   password VARCHAR NOT NULL,
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE signatures(
   id SERIAL PRIMARY KEY,
   sig TEXT NOT NULL CHECK (sig != ''),
   user_id INTEGER NOT NULL REFERENCES users(id),
   created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
 